### PR TITLE
@ 00:15 hs - FIX Syntax error: Bad for loop variable and stat: size in bytes

### PR DESCRIPTION
**Pull request by osiris**
Hi! in my Bash (versión 4.2.45) test don't pass! :(

```
spaceman-diff: generates ascii image diffs!
  it_shows_help_with_no_argv:                      [PASS]
  it_renders_diff:                                 [FAIL]
    + output='./spaceman-diff test/images/flag.png test/images/flag.png a190ba 100644 test/images/gooder-flag.png 000000 100644'
    + grep OLD:
    + ./spaceman-diff test/images/flag.png test/images/flag.png a190ba 100644 test/images/gooder-flag.png 000000 100644
    stat: no se puede leer la información del sistema de ficheros para «%z»: No existe el fichero o el directorio
    expr: error de sintaxis
    exit code 1
=========================================================
Tests:    2 | Passed:   1 | Failed:   1
```

after my commit:

```
spaceman-diff: generates ascii image diffs!
  it_shows_help_with_no_argv:                      [PASS]
  it_renders_diff:                                 [PASS]
=========================================================
Tests:    2 | Passed:   2 | Failed:   0
```

### CODE REVIEW

**Comment by holman** [comment]
I think this is a Mac thing- are you on Linux or something else? On my Mac:

``` sh
› stat -c %s README.md 
stat: illegal option -- c
```

I think I noticed this when I first wrote it, and then I didn't bother to dig deeper in it, heh.

**Comment by osiris** [comment]
El sáb, 25 jul 2015, Zach Holman decía:

> I think this is a Mac thing- are you on Linux or something else? On my Mac:
> 
> › stat -c %s README.md
> stat: illegal option -- c
> 
> I think I noticed this when I first wrote it, and then I didn't bother to dig
> deeper in it, heh.

Yes, I use Debian GNU/Linux on PC.

## 

::

  Osiris Alejandro Gomez (OSiRiS) osiris@gcoop.coop
  DC44 95D2 0D5D D544 FC1A F00F B308 A671 9237 D36C
  http://gcoop.coop | Cooperativa de Software Libre
  Julián Alvarez 958 CABA C1414DRT +54 11 4711-0055

**Comment by osiris** [comment]
maybe you can replace `stat -c %s` with `ls -l file | awk {print $5}`

**Comment by holman** [comment]
Merged the sequence change from this and then made the switch to `ls` as you suggested. Thanks for the help on this!

**Pull request merged**
